# Generated by Django 3.1.4 on 2021-01-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='Pune', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.IntegerField(default=9175834240),
        ),
    ]
