# Generated by Django 3.1.4 on 2021-01-17 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210117_2222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='customer_name',
        ),
    ]
